---
driver:
  name: ec2
  require_chef_omnibus: 12.14.60
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  iam_profile_name: test-ebs-attachment
  tags:
    Name: logserver-ubuntu-1404
    Type: test
    Env: public

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  driver_config:
    tags:
      Env: public

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[curl]
  - name: centos-6.7
    run_list:
    - recipe[yum]
    - recipe[curl]

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[kibana_test::default]
